---
title: "scRNAseq Analysis"
author: "IM"
date: "2025-03-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#load libraries
library(readr)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(gprofiler2)
library(ComplexHeatmap)
library(ggpubr)
library(RColorBrewer)
library(rlang)
library(circlize)
library(gprofiler2)
library(ComplexHeatmap)
library(Seurat)
library(biomaRt)
library(scico)
```

```{r Functions, echo=FALSE}
#define functions for exploring PLSR model in murine mammary development scRNAseq data
#data is from https://doi.org/10.1186/s13058-021-01445-4

#Function to prep scRNAseq data for PLSR signature analysis
prep_GSE<-function(directory=dir, dev_stage=stage){
  dat <- Read10X(data.dir = directory)
  dat_s <- CreateSeuratObject(counts = dat, project = "Visvader_Dev", min.cells = 3, min.features = 200)
  dat_s[["Developmental_Stage"]] <- dev_stage
  return(dat_s)
}

`%notin%` <- Negate(`%in%`)
```

```{r Data, echo=FALSE}
#read in 10x data from developmental stages, integrate and normalize
dat_1<-prep_GSE('Adult_BL6/', 'Adult_BL6')
dat_2<-prep_GSE('Embryonic_E18_ME/', 'Embryonic ME')
dat_3<-prep_GSE('Puberty_Ducts/','Puberty Ducts')
dat_4<-prep_GSE('Puberty_TerminalEndBuds/', 'Puberty_TerminalEndBuds')

#normalize all data
dat_list<-c(dat_1, dat_2, dat_3, dat_4)
dat_list <- lapply(X = dat_list, FUN = function(x) {
  x <- NormalizeData(x)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

#find integratin features and run pca using those features
features <- SelectIntegrationFeatures(object.list = dat_list)

dat_list <- lapply(X = dat_list, FUN = function(x) {
  x <- ScaleData(x, features = features, verbose = FALSE)
  x <- RunPCA(x, features = features, verbose = FALSE)
})

dat_anchors <- FindIntegrationAnchors(object.list = dat_list, anchor.features = features, reduction = "rpca")

#integrate data
dat_combined <- IntegrateData(anchorset = dat_anchors)

DefaultAssay(dat_combined) <- "integrated"

#run standard seurat normalization
dat_combined<-FindVariableFeatures(dat_combined)
all.genes<-rownames(dat_combined)
dat_combined <- ScaleData(dat_combined, verbose = FALSE, features = all.genes)
dat_combined <- RunPCA(dat_combined, npcs = 30, verbose = FALSE)
dat_combined <- RunUMAP(dat_combined, reduction = "pca", dims = 1:30)
dat_combined <- FindNeighbors(dat_combined, reduction = "pca", dims = 1:30)
dat_combined <- FindClusters(dat_combined, resolution = 0.5)

#UMAP by developmental stage
p1 <- DimPlot(dat_combined, reduction = "umap", group.by = "Developmental_Stage", raster = FALSE)
p2 <- DimPlot(dat_combined, reduction = "umap", label = TRUE, repel = TRUE, raster = FALSE)
p1 + p2
```

```{r expression of PLSR signatures}
#read in VIP signatures for migration and cell count PLSR
#data is available on https://github.com/mcleania/MCF10A_LigandCombination data directory
proliferation_geneset<-read_csv('Data/PLSR_VIP_Scores/CellCount_VIP_scores.csv')
migration_geneset<-read_csv('Data/PLSR_VIP_Scores/Motility_VIP_scores.csv')

#filter for top positively correlated VIPS
proliferation_geneset<-proliferation_geneset %>%
  filter(`combo_Y_proliferation.1 comps` > 0) %>%
  top_n(n=500, wt = VIP_SCORE)

migration_geneset<-migration_geneset %>%
  filter(`combo_Y_slope.1 comps` > 0) %>%
  top_n(n=500, wt = VIP_SCORE)

#convert genes in plsr models to mouse orthologs 
human = useMart("ensembl", dataset = "hsapiens_gene_ensembl")
mouse = useMart("ensembl", dataset = "mmusculus_gene_ensembl")
mgi2ensembl<-getBM(attributes = c('hgnc_symbol', 'ensembl_gene_id'), mart = human, values = proliferation_geneset$ensembl_gene_id)
ensembl2hgnc <- getBM(attributes = c("mmusculus_homolog_associated_gene_name", "ensembl_gene_id"), 
                        filters = "ensembl_gene_id", 
                        mart = human, 
                        value = mgi2ensembl$ensembl_gene_id)
merge_dat<-merge(mgi2ensembl, ensembl2hgnc)

proliferation_module<-proliferation_geneset %>%
  #select('hgnc_symbol') %>%
  left_join(merge_dat) %>%
  filter(mmusculus_homolog_associated_gene_name !='') 

migration_module<-migration_geneset%>%
 # select('hgnc_symbol') %>%
  left_join(merge_dat) %>%
  filter(mmusculus_homolog_associated_gene_name !='') 

#trim PLSR signature genes to genes with a mouse ortholog contained in most variable genes in mouse dataset
t_prolif<-setdiff(proliferation_module$mmusculus_homolog_associated_gene_name, rownames(dat_combined))
t_migration<-setdiff(migration_module$mmusculus_homolog_associated_gene_name, rownames(dat_combined))

DefaultAssay(dat_combined)<-'integrated'
top10 <- head(VariableFeatures(dat_combined), 1000)

proliferation_module<-proliferation_geneset %>%
  #select('hgnc_symbol') %>%
  left_join(merge_dat) %>%
  filter(mmusculus_homolog_associated_gene_name !='') %>%
  filter(mmusculus_homolog_associated_gene_name %notin% t_prolif)%>%
  filter(mmusculus_homolog_associated_gene_name %in% top10)

migration_module<-migration_geneset%>%
 # select('hgnc_symbol') %>%
  left_join(merge_dat) %>%
  filter(mmusculus_homolog_associated_gene_name !='') %>%
  filter(mmusculus_homolog_associated_gene_name %notin% t_migration)%>%
  filter(mmusculus_homolog_associated_gene_name %in% top10)

#Add module scores
dat_combined_new = JoinLayers(dat_combined)
DefaultAssay(dat_combined)<-'RNA'

dat_combined <- AddModuleScore(
  object = dat_combined,
  features = proliferation_module$mmusculus_homolog_associated_gene_name,
  name = 'Proliferation_module_n',
  ctrl = 75
)

dat_combined <- AddModuleScore(
  object = dat_combined,
  features = migration_module$mmusculus_homolog_associated_gene_name,
  name = 'Migration_module',
  ctrl = 75
)

#Violin and feature plot of module scores by developmental stage
VlnPlot(dat_combined, features = c('Proliferation_module1'), group.by = 'Developmental_Stage', raster = FALSE, pt.size = 0)

```

```{r Ductal Epithelium Analysis, echo=FALSE}
#investigate ductal epithelium in puberty
Puberty_Ducts_s<-dat_3

#renormalize data
Puberty_Ducts_s[["percent.mt"]] <- PercentageFeatureSet(Puberty_Ducts_s, pattern = "^MT-")
Puberty_Ducts_s <- subset(Puberty_Ducts_s, subset = nFeature_RNA > 2000)
Puberty_Ducts_s <- NormalizeData(Puberty_Ducts_s)
Puberty_Ducts_s <- FindVariableFeatures(Puberty_Ducts_s, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(Puberty_Ducts_s)
Puberty_Ducts_s <- ScaleData(Puberty_Ducts_s, features = all.genes)

#dimensional reduction
Puberty_Ducts_s <- RunPCA(Puberty_Ducts_s, features = VariableFeatures(object = Puberty_Ducts_s))
Puberty_Ducts_s <- JackStraw(Puberty_Ducts_s, num.replicate = 100)
Puberty_Ducts_s <- ScoreJackStraw(Puberty_Ducts_s)
Puberty_Ducts_s <- FindNeighbors(Puberty_Ducts_s, dims = 1:20)
Puberty_Ducts_s <- FindClusters(Puberty_Ducts_s, resolution = .05)
Puberty_Ducts_s <- RunUMAP(Puberty_Ducts_s, dims = 1:20)

#visualize clusters
DimPlot(Puberty_Ducts_s, reduction = "umap")

#rename clusters based on cell markers
cluster.ids <- c("Basal", "Mature Luminal", "Luminal Progenitors") 
names(cluster.ids) <- levels(Puberty_Ducts_s)
Puberty_Ducts_s <- RenameIdents(Puberty_Ducts_s, cluster.ids)

#add PLSR module scores
top10 <- head(VariableFeatures(Puberty_Ducts_s), 1000)

proliferation_module<-proliferation_geneset %>%
  #select('hgnc_symbol') %>%
  left_join(merge_dat) %>%
  filter(mmusculus_homolog_associated_gene_name !='') %>%
  filter(mmusculus_homolog_associated_gene_name %notin% t_prolif)%>%
  filter(mmusculus_homolog_associated_gene_name %in% top10)

migration_module<-migration_geneset%>%
 # select('hgnc_symbol') %>%
  left_join(merge_dat) %>%
  filter(mmusculus_homolog_associated_gene_name !='') %>%
  filter(mmusculus_homolog_associated_gene_name %notin% t_migration)%>%
  filter(mmusculus_homolog_associated_gene_name %in% top10)

Puberty_Ducts_s <- AddModuleScore(
  object = Puberty_Ducts_s,
  features = proliferation_module$mmusculus_homolog_associated_gene_name,
  name = 'Proliferation_module'
)
Puberty_Ducts_s <- AddModuleScore(
  object = Puberty_Ducts_s,
  features = migration_module$mmusculus_homolog_associated_gene_name,
  name = 'Migration_module'
)

#violin plot of module expression
VlnPlot(Puberty_Ducts_s, features = c('Proliferation_module1'), raster = FALSE, pt.size = 0) 

#feature plot of module expression
FeaturePlot(Puberty_Ducts_s, features = c('Proliferation_module1'), raster = F, label = T, min.cutoff = -1, max.cutoff = 1) & scale_color_gradientn(colors = scico(palette = 'vik', n = 4, direction = 1))

#find overlap between basal markers and cell count signature
basal_markers<-FindMarkers(Puberty_Ducts_s, ident.1 = 'Basal', only.pos = T)

overlap_prolif_basal<-proliferation_module %>%
  filter(mmusculus_homolog_associated_gene_name %in% rownames(basal_markers[1:1600,]))

overlap_prolif_ml_order<-basal_markers%>%
  rownames_to_column('symbol') %>%
  filter(symbol %in% overlap_prolif_basal$mmusculus_homolog_associated_gene_name) %>%
  arrange(desc(avg_log2FC))


t<-DoHeatmap(Puberty_Ducts_s, features = overlap_prolif_ml_order$symbol[1:20]) +
  theme(plot.margin = margin(0,2,0,1.5, "cm"))

```

